# docker-compose --env-file ../../.env up -d
services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - ../../.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    labels:
      - traefik.enable=true
      - traefik.docker.network=evoagi_default
      - traefik.constraint-label=evoagi_default
      - traefik.http.routers.${STACK_NAME?Variable not set}-redis-http.rule=Host(`redis.${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-redis-http.entrypoints=http
      - traefik.http.routers.${STACK_NAME?Variable not set}-redis-http.middlewares=https-redirect
      - traefik.http.routers.${STACK_NAME?Variable not set}-redis-https.rule=Host(`redis.${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-redis-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME?Variable not set}-redis-https.tls=true
      - traefik.http.routers.${STACK_NAME?Variable not set}-redis-https.tls.certresolver=le
      - traefik.http.services.${STACK_NAME?Variable not set}-redis.loadbalancer.server.port=6379

networks:
  evoagi_default:
    # Allow setting it to false for testing
    external: true
volumes:
  app-db-data:
  app-qdrant-data:
  app-backend-model-cache:
  app-upload-data:
