"""update annotation tabel2

Revision ID: 034e9dfee5a8
Revises: 8b93d9fa8047
Create Date: 2024-11-06 10:35:55.280710

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '034e9dfee5a8'
down_revision = '8b93d9fa8047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('annotation_task_id_fkey', 'annotation', type_='foreignkey')
    op.drop_column('annotation', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('annotation_task_id_fkey', 'annotation', 'task', ['task_id'], ['task_id'])
    # ### end Alembic commands ###
