"""update annotation tabel2

Revision ID: 200783bed0b6
Revises: 940710c47e2a
Create Date: 2024-10-30 11:50:33.773019

"""

# revision identifiers, used by Alembic.
revision = "200783bed0b6"
down_revision = "940710c47e2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
