"""update workflow tabel3

Revision ID: 3a283e23a07e
Revises: a189f1e17a2e
Create Date: 2024-11-02 17:59:33.355619

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3a283e23a07e'
down_revision = 'a189f1e17a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_data', sa.Column('input_data_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'processed_data', 'processed_data', ['input_data_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processed_data', type_='foreignkey')
    op.drop_column('processed_data', 'input_data_id')
    # ### end Alembic commands ###
