"""fix relationships

Revision ID: 3f2445dbcfb7
Revises: db0c34caf410
Create Date: 2024-11-05 09:01:41.212683

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3f2445dbcfb7'
down_revision = 'db0c34caf410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
