"""fix relationships

Revision ID: 5f352871bd3c
Revises: 3f2445dbcfb7
Create Date: 2024-11-05 09:03:13.028490

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5f352871bd3c'
down_revision = '3f2445dbcfb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
