"""fix data relationships2

Revision ID: 6a7d26a72c98
Revises: 5f352871bd3c
Create Date: 2024-11-05 09:04:45.238017

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6a7d26a72c98'
down_revision = '5f352871bd3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
