"""update annotation tabel

Revision ID: 8b93d9fa8047
Revises: 5d4f0e6b5bf3
Create Date: 2024-11-06 09:57:52.607620

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8b93d9fa8047'
down_revision = '5d4f0e6b5bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('processing_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('annotation', sa.Column('workflow_execution_id', sa.Integer(), nullable=True))
    op.add_column('annotation', sa.Column('node_execution_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'annotation', 'workflow_node_execution', ['node_execution_id'], ['id'])
    op.create_foreign_key(None, 'annotation', 'workflow_execution', ['workflow_execution_id'], ['execution_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'annotation', type_='foreignkey')
    op.drop_constraint(None, 'annotation', type_='foreignkey')
    op.drop_column('annotation', 'node_execution_id')
    op.drop_column('annotation', 'workflow_execution_id')
    op.drop_column('annotation', 'processing_stage')
    # ### end Alembic commands ###
