"""update annotation tabel

Revision ID: 940710c47e2a
Revises: 9da253bce8df
Create Date: 2024-10-30 11:48:34.882093

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "940710c47e2a"
down_revision = "9da253bce8df"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "annotation",
        sa.Column("points", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "annotation",
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "annotation",
        sa.Column("labelme_data", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column("annotation", "type", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("annotation", "result")
    op.drop_column("annotation", "predicted_by")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "annotation",
        sa.Column("predicted_by", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "annotation",
        sa.Column("result", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.alter_column("annotation", "type", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("annotation", "labelme_data")
    op.drop_column("annotation", "color")
    op.drop_column("annotation", "points")
    # ### end Alembic commands ###
