"""modify label

Revision ID: 9da253bce8df
Revises: 1fed1e9319e5
Create Date: 2024-10-29 15:08:41.872666

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9da253bce8df"
down_revision = "1fed1e9319e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("label", "id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "label", sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
