"""update workflow tabel2

Revision ID: a189f1e17a2e
Revises: 8da2477d07b6
Create Date: 2024-11-02 11:32:38.768551

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a189f1e17a2e'
down_revision = '8da2477d07b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processed_data', 'original_data_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workflow_execution', 'workflow_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workflow_node_execution', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_node_execution', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('workflow_execution', 'workflow_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('processed_data', 'original_data_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
