"""new models1105

Revision ID: db0c34caf410
Revises: d2001cebf0a6
Create Date: 2024-11-05 08:59:42.951434

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db0c34caf410'
down_revision = 'd2001cebf0a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('original_data_id', sa.Integer(), nullable=True))
    op.add_column('data', sa.Column('workflow_execution_id', sa.Integer(), nullable=True))
    op.add_column('data', sa.Column('node_execution_id', sa.Integer(), nullable=True))
    op.add_column('data', sa.Column('processing_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('data', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('data', sa.Column('metadata_', sa.JSON(), nullable=False))
    op.create_foreign_key(None, 'data', 'data', ['original_data_id'], ['data_id'])
    op.alter_column('workflow_node_execution', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_node_execution', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.drop_column('data', 'metadata_')
    op.drop_column('data', 'category')
    op.drop_column('data', 'processing_stage')
    op.drop_column('data', 'node_execution_id')
    op.drop_column('data', 'workflow_execution_id')
    op.drop_column('data', 'original_data_id')
    # ### end Alembic commands ###
